class CommonMessage:
    # Audio related
    AUDIO_NOT_FOUND = "AUDIO_NOT_FOUND"
    AUDIO_NOT_TRANSCRIBED = "AUDIO_NOT_TRANSCRIBED"
    AUDIO_FILE_TOO_LARGE = "AUDIO_FILE_TOO_LARGE"
    AUDIO_FILE_INVALID_FORMAT = "AUDIO_FILE_INVALID_FORMAT"
    AUDIO_FILE_SAVE_FAILED = "AUDIO_FILE_SAVE_FAILED"
    AUDIO_FILE_NOT_FOUND_ON_DISK = "AUDIO_FILE_NOT_FOUND_ON_DISK"
    
    # Note related
    NOTE_NOT_FOUND = "NOTE_NOT_FOUND"
    NOTE_CREATE_FAILED = "NOTE_CREATE_FAILED"
    NOTE_UPDATE_FAILED = "NOTE_UPDATE_FAILED"
    NOTE_DELETE_FAILED = "NOTE_DELETE_FAILED"
    
    # Transcription related
    TRANSCRIPTION_SERVICE_UNAVAILABLE = "TRANSCRIPTION_SERVICE_UNAVAILABLE"
    TRANSCRIPTION_FAILED = "TRANSCRIPTION_FAILED"
    TRANSCRIPTION_SAVE_FAILED = "TRANSCRIPTION_SAVE_FAILED"
    TRANSCRIPTION_GCS_REQUIRED = "TRANSCRIPTION_GCS_REQUIRED"
    TRANSCRIPTION_GCS_FAILED = "TRANSCRIPTION_GCS_FAILED"
    
    # AI/Summary related
    SUMMARY_GENERATION_FAILED = "SUMMARY_GENERATION_FAILED"
    
    # Google Cloud API related
    GOOGLE_CLOUD_API_ERROR = "GOOGLE_CLOUD_API_ERROR"
    
    # Success messages
    NOTE_DELETED_SUCCESS = "NOTE_DELETED_SUCCESS"
    SUMMARY_CREATED_SUCCESS = "SUMMARY_CREATED_SUCCESS"